name: Unity Build (Linux)

on:
  push:
    branches: [DevOps]
  pull_request:
    branches: [DevOps]

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/manifest.json') }}

      - name: Build project
        uses: unity-ci/build@v3
        with:
          unityVersion: 6000.0.50f1
          targetPlatform: StandaloneLinux64

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UnityBuild-Linux
          path: build/StandaloneLinux64
