name: Unity Build (Linux)

on:
  push:
    branches: [DevOps]
  pull_request:
    branches: [DevOps]

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Unity
        uses: game-ci/unity-setup@v4
        with:
          unityVersion: 6000.0.50f1

      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.10f1
          targetPlatform: StandaloneLinux64

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UnityBuild-Linux
          path: build/StandaloneLinux64
