name: Lint and Autoformat C# Scripts

on:
  push:
    branches: [ DevOps ]
  pull_request:
    branches: [ DevOps ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Node.js (for csharpier)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install csharpier
      run: npm install -g csharpier

    - name: Run csharpier on C# files
      run: |
        csharpier Assets/Scripts/**/*.cs

    - name: Commit and push changes if any
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --cached --quiet || git commit -m "chore: autoformat C# scripts"
        git push
